# Numpy

In [1]:
1. 길이가 10인 0-벡터를 만드세요.

2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인
   벡터를 만드세요.

3. 10 부터 49까지의 값을 가지는 벡터를 만드세요.

4. 위(3번) 벡터의 순서를 바꾸세요.

5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를
   만드세요.

7. 3x3 단위 행렬(identity matrix)을 만드세요

8. 난수 원소를 가지는 3x3 행렬을 만드세요

9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

SyntaxError: invalid syntax (<ipython-input-1-4a4214a4b2c6>, line 1)

In [11]:
#1. 길이가 10인 0-벡터를 만드세요.

import numpy as np

np.zeros(shape=(10,),dtype=np.int8)



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [16]:
#2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.
 
np.eye(1,10,k=4)


array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [18]:
# 3. 10 부터 49까지의 값을 가지는 벡터를 만드세요.

np.arange(10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [40]:
# 4. 위(3번) 벡터의 순서를 바꾸세요.

a = np.arange(10,50,1)
np.sort(a)[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [41]:
#5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

matrix = [[0,1,2],[3,4,5],[6,7,8]]
np.array(matrix, int)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
##6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

vector = [1,2,0,0,4,0]
a = np.array(vector)
b = a>0
a[b]

array([1, 2, 4])

In [51]:
### 7. 3x3 단위 행렬(identity matrix)을 만드세요.

np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
## 8. 난수 원소를 가지는 3x3 행렬을 만드세요.
import numpy as np
np.random.seed(604)
a = np.random.uniform(0,10,9).reshape(3,3)
b = np.array(a,int)
b

array([[2, 1, 6],
       [1, 1, 5],
       [7, 9, 3]])

In [31]:
## 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

a[np.argmax(a)//3, np.argmax(a)%3],np.argmax(a)

(9.709985452208038, 7)

In [32]:
a[np.argmin(a)//3, np.argmin(a)%3],np.argmin(a)

(1.0216826983588667, 4)

In [33]:
## 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

print('열의평균 : %s'%b.mean(axis=0))
print('행의평균 : %s'%b.mean(axis=1))

열의평균 : [3.33333333 3.66666667 4.66666667]
행의평균 : [3.         2.33333333 6.33333333]
